### ISSUE TITLE
Parameter Handling

### ISSUE THREAD

**Issue by johnnadratowski** [Selvatico/go-mocket#2]
The subject is vague, but hear me out.  Parameter handling is broken.  If you have '%' in a parameter it will cause the output to be formatted incorrectly by formatting the previously formatted string.  Offending code here: 

https://github.com/Selvatico/go-mocket/blob/master/stmt.go#L111

I was in the middle of writing a PR to make it handle the question marks properly, but then I noticed this test: 

https://github.com/Selvatico/go-mocket/blob/master/response_test.go#L154

Which claimed to handle postgres dollar-style parameters as well, however the test never does anything with the parameters (only a partial match on the query string).

This got me thinking.  I'm not sure that the code (in stmt.go line 111) should be trying to place the parameters in the query string at all.  Technically, the database itself receives the parameters along with the parameterized query and does the parsing itself, at least in the case of Postgres (I'd imagine other DBs do it this way as well): https://www.pgcon.org/2014/schedule/attachments/330_postgres-for-the-wire.pdf

I think it would be easier to use as well if it didn't attempt to replace the parameters, as you could do a query match + parameters match to get a more precise match.

If you agree, I can submit a PR to remove the code in stmt.go line 111.

**Comment by Selvatico** [comment]
Hello @johnnadratowski , let me check today evening and I will back to you.

**Comment by Selvatico** [comment]
@johnnadratowski I checked, but forgot to answer you on this -  problem is that driver itself is the layer after SQL package and in case GOROM (which was initial intention to create this package) the resulting SQL query could look different if you passing raw query and passing through some Object-Oriented way and depending from DB. We can 2 scenarios: you can provide me small code snippets to create the fix or you can submit pull-request. What suits better for you.

**Comment by Selvatico** [comment]
Closing.
