### ISSUE TITLE
Aggregate SQL function support

### ISSUE THREAD

**Issue by buildscientist** [Selvatico/go-mocket#6]
@Selvatico Does go-mocket have support for aggregate SQL functions like count()? 

In GORM if I'm doing something like: 

``	dbHandle.Model(&models.User{}).Where("user_id = ?", username).Count(&count) ``

How do I mock this?

**Comment by buildscientist** [comment]
@Selvatico please ignore this - I was able to figure this out. 

If anyone else is reading this: 

Aggregate functions like COUNT, AVERAGE all return 1 row containing the value returned from that function. 

To mock the DB result you'd do something like: 

```go
commonReply := []map[string]interface{}{{"count": "1"}}
go_mocket.Catcher.Reset().NewMock().WithQuery(`SELECT count(*) FROM "users" WHERE`).WithReply(commandReply) 
```

You'd want to replace the keyword "count" with whatever your DB returns as a row header for that aggregate function. 

Additionally - turning on go-mocket logging by setting: 

```go
GlobalMock.Logging = true
```
is important because you want to capture the exact SQL statement GORM is executing.

**Comment by Selvatico** [comment]
@buildscientist nice. 👍
